/**
 * api/species-profile.js — Rich species profiles generated by Claude Haiku
 * 
 * Pattern: Generate once, cache forever (per season).
 * Static content (field marks, habitat, range) never changes.
 * Seasonal context (what's it doing NOW) regenerates quarterly.
 * Real-time sightings from eBird overlay on top (not cached here).
 */

const { Redis } = require('@upstash/redis');
const { getSpeciesObservations, getRecentObservations, getNotableSightings } = require('../lib/ebird');
const { getBestImage, getINatPhotos } = require('../lib/media');

const ANTHROPIC_KEY = process.env.ANTHROPIC_API_KEY;
const PROFILE_TTL = 86400 * 60; // 60 days

let redis;
function getRedis() {
  if (!redis) {
    redis = new Redis({
      url: process.env.UPSTASH_REDIS_URL,
      token: process.env.UPSTASH_REDIS_TOKEN,
    });
  }
  return redis;
}

function getSeason() {
  const m = new Date().getMonth();
  if (m >= 2 && m <= 4) return 'spring';
  if (m >= 5 && m <= 7) return 'summer';
  if (m >= 8 && m <= 10) return 'fall';
  return 'winter';
}

module.exports = async (req, res) => {
  try {
    const code = req.query.code;        // eBird species code
    const name = req.query.name;        // common name
    const sciName = req.query.sci;      // scientific name
    
    if (!code || !name) {
      return res.status(400).json({ error: 'code and name params required' });
    }

    const season = getSeason();
    const cacheKey = `birding:profile:${code}:${season}`;

    // Check for cached profile TEXT (images are always fetched fresh)
    let profile = null;
    try {
      const r = getRedis();
      const cached = await r.get(cacheKey);
      if (cached) {
        profile = typeof cached === 'string' ? JSON.parse(cached) : cached;
      }
    } catch (e) { console.warn('Redis read:', e.message); }

    // Generate profile text with Haiku if not cached
    if (!profile) {
      profile = await generateProfile(code, name, sciName || '', season);
      
      // Cache ONLY the text content (no images)
      const textOnly = {
        speciesCode: code,
        comName: name,
        sciName: sciName || '',
        season,
        ...profile,
      };
      try {
        const r = getRedis();
        await r.set(cacheKey, JSON.stringify(textOnly), { ex: PROFILE_TTL });
      } catch (e) { console.warn('Redis write:', e.message); }
    }

    // ALWAYS fetch images and sightings fresh (never cached with profile)
    const [image, recentSightings, inatPhotos] = await Promise.all([
      getBestImage(code, name),
      getRecentSightings(code),
      getINatPhotos(sciName || name, { perPage: 4 }).catch(() => []),
    ]);

    res.status(200).json({
      speciesCode: code,
      comName: name,
      sciName: sciName || '',
      season,
      image,
      inatPhotos,
      recentSightings,
      cached: !!profile?.generatedBy,
      ...profile,
    });
  } catch (err) {
    console.error('Species profile error:', err);
    res.status(500).json({ error: err.message });
  }
};

async function getRecentSightings(speciesCode) {
  try {
    // Query BOTH endpoints and merge - notable sightings often don't appear
    // in the regular species endpoint for rare birds
    const [speciesObs, notableObs] = await Promise.all([
      getSpeciesObservations('US-MI', speciesCode, { back: 30 }).catch(() => []),
      getNotableSightings('US-MI', { back: 14, maxResults: 50 }).catch(() => []),
    ]);

    // Filter notable to just this species
    const notableForSpecies = (notableObs || []).filter(o => o.speciesCode === speciesCode);

    // Merge and deduplicate by location+date
    const all = [...(speciesObs || []), ...notableForSpecies];
    const seen = new Map();
    for (const o of all) {
      const key = `${o.locId || o.locName}:${o.obsDt}`;
      if (!seen.has(key)) seen.set(key, o);
    }

    return Array.from(seen.values())
      .sort((a, b) => new Date(b.obsDt?.replace(' ', 'T') || 0) - new Date(a.obsDt?.replace(' ', 'T') || 0))
      .slice(0, 20)
      .map(o => ({
        locName: o.locName,
        obsDt: o.obsDt,
        howMany: o.howMany || null,
        lat: o.lat,
        lng: o.lng,
        locId: o.locId,
        subnational2Code: o.subnational2Code,
      }));
  } catch (e) {
    return [];
  }
}

async function generateProfile(code, name, sciName, season) {
  if (!ANTHROPIC_KEY) {
    return getStaticProfile(name, season);
  }

  const months = {
    spring: 'March through May',
    summer: 'June through August', 
    fall: 'September through November',
    winter: 'December through February',
  };

  const prompt = `You are a Michigan birding expert writing a species profile for "${name}" (${sciName || code}). The current season is ${season} (${months[season]}).

Write a JSON object with these fields. Be specific to MICHIGAN. Write naturally, no bullet points. Each field should be 2-4 sentences of flowing prose.

{
  "michiganStatus": "Is this bird a year-round resident, summer breeder, winter visitor, or passage migrant in Michigan? How common is it? Any population trends?",
  "rightNow": "What is this species doing RIGHT NOW in Michigan during ${season}? Are they migrating through, nesting, staging, wintering? Be very specific to the current time of year.",
  "whereToFind": "Best specific locations in Michigan to find this species right now. Name actual places: state parks, wildlife areas, counties, habitat types.",
  "fieldMarks": "Key identification features. What should a birder look for? Distinguish from similar species. Include size, plumage, behavior, and voice.",
  "habitat": "What habitats does this species prefer in Michigan? Be specific: marsh types, forest types, edge habitats, urban areas, agricultural fields.",
  "nesting": "Nesting habits in Michigan if it breeds here. Timing, nest type, clutch size, habitat. If it doesn't breed in Michigan, say where it breeds.",
  "conservation": "Conservation status and any Michigan-specific concerns or success stories.",
  "funFact": "One compelling or surprising fact about this species that would interest a birder."
}

Return ONLY valid JSON. No markdown, no backticks, no preamble.`;

  try {
    const aiRes = await fetch('https://api.anthropic.com/v1/messages', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'x-api-key': ANTHROPIC_KEY,
        'anthropic-version': '2023-06-01',
      },
      body: JSON.stringify({
        model: 'claude-haiku-4-5-20251001',
        max_tokens: 1000,
        messages: [{ role: 'user', content: prompt }],
      }),
    });

    if (!aiRes.ok) {
      console.error('Haiku API error:', aiRes.status);
      return getStaticProfile(name, season);
    }

    const aiData = await aiRes.json();
    const text = (aiData.content?.[0]?.text || '').trim();
    
    // Parse JSON, strip any markdown fencing
    const clean = text.replace(/```json\s*/g, '').replace(/```\s*/g, '').trim();
    const profile = JSON.parse(clean);
    return { ...profile, generatedBy: 'haiku' };
  } catch (e) {
    console.error('Profile generation error:', e.message);
    return getStaticProfile(name, season);
  }
}

function getStaticProfile(name, season) {
  return {
    michiganStatus: `${name} is found in Michigan. Check eBird for current frequency and distribution data.`,
    rightNow: `During ${season}, check local hotspots and eBird for the latest reports of ${name} across Michigan.`,
    whereToFind: 'Search eBird hotspots in your area for recent sightings. Saginaw Bay, Tawas Point, and Pointe Mouillee are productive year-round.',
    fieldMarks: `Consult a field guide like Sibley or Kaufman for detailed identification features of ${name}.`,
    habitat: 'Habitat preferences vary by species and season. Check species accounts on All About Birds (allaboutbirds.org) for detailed information.',
    nesting: 'Nesting information varies. See Birds of the World (birdsoftheworld.org) for comprehensive breeding data.',
    conservation: 'Check the IUCN Red List and Partners in Flight for current conservation status.',
    funFact: `${name} is one of the many fascinating species found in Michigan's diverse habitats.`,
    generatedBy: 'static',
  };
}
